# Informações da câmera USB utilizada

image_width: 1280
image_height: 720
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1120.6986 ,    0.     ,  628.12751,
            0.     , 1120.16507,  350.3612 ,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.036590, -0.086235, -0.003724, -0.005789, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1123.10413,    0.     ,  620.84507,    0.     ,
            0.     , 1127.91516,  347.79388,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
